/* Generated By:JavaCC: Do not edit this line. XParserVisitor.java Version 5.0 */
package fr.upsud.lri.xqparser;

public interface XParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=9aa0fbd990b9cab62b74b25388befc19 (do not edit this line) */
