/* Generated By:JavaCC: Do not edit this line. XParserTreeConstants.java Version 5.0 */
package fr.upsud.lri.xqparser;

public interface XParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTQUERYLIST = 1;
  public int JJTMODULE = 2;
  public int JJTVERSIONDECL = 3;
  public int JJTSTRINGLITERAL = 4;
  public int JJTMAINMODULE = 5;
  public int JJTLIBRARYMODULE = 6;
  public int JJTMODULEDECL = 7;
  public int JJTPROLOG = 8;
  public int JJTSETTER = 9;
  public int JJTIMPORT = 10;
  public int JJTSEPARATOR = 11;
  public int JJTNAMESPACEDECL = 12;
  public int JJTBOUNDARYSPACEDECL = 13;
  public int JJTDEFAULTNAMESPACEDECL = 14;
  public int JJTOPTIONDECL = 15;
  public int JJTORDERINGMODEDECL = 16;
  public int JJTEMPTYORDERDECL = 17;
  public int JJTGREATEST = 18;
  public int JJTLEAST = 19;
  public int JJTCOPYNAMESPACESDECL = 20;
  public int JJTPRESERVEMODE = 21;
  public int JJTINHERITMODE = 22;
  public int JJTDEFAULTCOLLATIONDECL = 23;
  public int JJTBASEURIDECL = 24;
  public int JJTSCHEMAIMPORT = 25;
  public int JJTSCHEMAPREFIX = 26;
  public int JJTMODULEIMPORT = 27;
  public int JJTVARDECL = 28;
  public int JJTEXTERNAL = 29;
  public int JJTCONSTRUCTIONDECL = 30;
  public int JJTFUNCTIONDECL = 31;
  public int JJTPARAMLIST = 32;
  public int JJTPARAM = 33;
  public int JJTENCLOSEDEXPR = 34;
  public int JJTLBRACE = 35;
  public int JJTRBRACE = 36;
  public int JJTQUERYBODY = 37;
  public int JJTEXPR = 38;
  public int JJTVOID = 39;
  public int JJTFLWOREXPR10 = 40;
  public int JJTFORCLAUSE = 41;
  public int JJTPOSITIONALVAR = 42;
  public int JJTLETCLAUSE = 43;
  public int JJTWHERECLAUSE = 44;
  public int JJTORDERBYCLAUSE = 45;
  public int JJTORDERSPECLIST = 46;
  public int JJTORDERSPEC = 47;
  public int JJTORDERMODIFIER = 48;
  public int JJTASCENDING = 49;
  public int JJTDESCENDING = 50;
  public int JJTQUANTIFIEDEXPR = 51;
  public int JJTTYPESWITCHEXPR = 52;
  public int JJTCASECLAUSE = 53;
  public int JJTIFEXPR = 54;
  public int JJTOREXPR = 55;
  public int JJTANDEXPR = 56;
  public int JJTCOMPARISONEXPR = 57;
  public int JJTRANGEEXPR = 58;
  public int JJTADDITIVEEXPR = 59;
  public int JJTMULTIPLICATIVEEXPR = 60;
  public int JJTUNIONEXPR = 61;
  public int JJTINTERSECTEXCEPTEXPR = 62;
  public int JJTINSTANCEOFEXPR = 63;
  public int JJTTREATEXPR = 64;
  public int JJTCASTABLEEXPR = 65;
  public int JJTCASTEXPR = 66;
  public int JJTUNARYEXPR = 67;
  public int JJTMINUS = 68;
  public int JJTPLUS = 69;
  public int JJTVALIDATEEXPR = 70;
  public int JJTVALIDATIONMODE = 71;
  public int JJTEXTENSIONEXPR = 72;
  public int JJTPRAGMA = 73;
  public int JJTPRAGMAOPEN = 74;
  public int JJTS = 75;
  public int JJTSFORPRAGMA = 76;
  public int JJTPRAGMACLOSE = 77;
  public int JJTPRAGMACONTENTS = 78;
  public int JJTEXTENSIONCONTENTCHAR = 79;
  public int JJTPATHEXPR = 80;
  public int JJTSLASH = 81;
  public int JJTSLASHSLASH = 82;
  public int JJTSTEPEXPR = 83;
  public int JJTFORWARDAXIS = 84;
  public int JJTABBREVFORWARDSTEP = 85;
  public int JJTREVERSEAXIS = 86;
  public int JJTABBREVREVERSESTEP = 87;
  public int JJTNODETEST = 88;
  public int JJTNAMETEST = 89;
  public int JJTWILDCARD = 90;
  public int JJTNCNAMECOLONSTAR = 91;
  public int JJTSTARCOLONNCNAME = 92;
  public int JJTPREDICATELIST = 93;
  public int JJTPREDICATE = 94;
  public int JJTINTEGERLITERAL = 95;
  public int JJTDECIMALLITERAL = 96;
  public int JJTDOUBLELITERAL = 97;
  public int JJTVARNAME = 98;
  public int JJTPARENTHESIZEDEXPR = 99;
  public int JJTCONTEXTITEMEXPR = 100;
  public int JJTORDEREDEXPR = 101;
  public int JJTUNORDEREDEXPR = 102;
  public int JJTFUNCTIONCALL = 103;
  public int JJTCONSTRUCTOR = 104;
  public int JJTDIRECTCONSTRUCTOR = 105;
  public int JJTDIRELEMCONSTRUCTOR = 106;
  public int JJTLESSTHANOPORTAGO = 107;
  public int JJTSTARTTAGOPEN = 108;
  public int JJTTAGQNAME = 109;
  public int JJTEMPTYTAGCLOSE = 110;
  public int JJTSTARTTAGCLOSE = 111;
  public int JJTENDTAGQNAME = 112;
  public int JJTDIRATTRIBUTELIST = 113;
  public int JJTVALUEINDICATOR = 114;
  public int JJTDIRATTRIBUTEVALUE = 115;
  public int JJTOPENQUOT = 116;
  public int JJTESCAPEQUOT = 117;
  public int JJTCLOSEQUOT = 118;
  public int JJTOPENAPOS = 119;
  public int JJTESCAPEAPOS = 120;
  public int JJTCLOSEAPOS = 121;
  public int JJTQUOTATTRVALUECONTENT = 122;
  public int JJTQUOTATTRCONTENTCHAR = 123;
  public int JJTAPOSATTRVALUECONTENT = 124;
  public int JJTAPOSATTRCONTENTCHAR = 125;
  public int JJTDIRELEMCONTENT = 126;
  public int JJTELEMENTCONTENTCHAR = 127;
  public int JJTCOMMONCONTENT = 128;
  public int JJTPREDEFINEDENTITYREF = 129;
  public int JJTCHARREF = 130;
  public int JJTLCURLYBRACEESCAPE = 131;
  public int JJTRCURLYBRACEESCAPE = 132;
  public int JJTDIRCOMMENTCONSTRUCTOR = 133;
  public int JJTXMLCOMMENTSTARTFORELEMENTCONTENT = 134;
  public int JJTXMLCOMMENTSTART = 135;
  public int JJTXMLCOMMENTEND = 136;
  public int JJTDIRCOMMENTCONTENTS = 137;
  public int JJTCOMMENTCONTENTCHAR = 138;
  public int JJTCOMMENTCONTENTCHARDASH = 139;
  public int JJTDIRPICONSTRUCTOR = 140;
  public int JJTPROCESSINGINSTRUCTIONSTARTFORELEMENTCONTENT = 141;
  public int JJTPROCESSINGINSTRUCTIONSTART = 142;
  public int JJTPITARGET = 143;
  public int JJTSFORPI = 144;
  public int JJTPROCESSINGINSTRUCTIONEND = 145;
  public int JJTDIRPICONTENTS = 146;
  public int JJTPICONTENTCHAR = 147;
  public int JJTCDATASECTION = 148;
  public int JJTCDATASECTIONSTARTFORELEMENTCONTENT = 149;
  public int JJTCDATASECTIONSTART = 150;
  public int JJTCDATASECTIONEND = 151;
  public int JJTCDATASECTIONCONTENTS = 152;
  public int JJTCDATASECTIONCHAR = 153;
  public int JJTCOMPUTEDCONSTRUCTOR = 154;
  public int JJTCOMPDOCCONSTRUCTOR = 155;
  public int JJTCOMPELEMCONSTRUCTOR = 156;
  public int JJTCONTENTEXPR = 157;
  public int JJTCOMPATTRCONSTRUCTOR = 158;
  public int JJTCOMPTEXTCONSTRUCTOR = 159;
  public int JJTCOMPCOMMENTCONSTRUCTOR = 160;
  public int JJTCOMPPICONSTRUCTOR = 161;
  public int JJTSINGLETYPE = 162;
  public int JJTTYPEDECLARATION = 163;
  public int JJTSEQUENCETYPE = 164;
  public int JJTOCCURRENCEINDICATOR = 165;
  public int JJTITEMTYPE = 166;
  public int JJTATOMICTYPE = 167;
  public int JJTANYKINDTEST = 168;
  public int JJTDOCUMENTTEST = 169;
  public int JJTTEXTTEST = 170;
  public int JJTCOMMENTTEST = 171;
  public int JJTPITEST = 172;
  public int JJTATTRIBUTETEST = 173;
  public int JJTATTRIBNAMEORWILDCARD = 174;
  public int JJTSCHEMAATTRIBUTETEST = 175;
  public int JJTATTRIBUTEDECLARATION = 176;
  public int JJTELEMENTTEST = 177;
  public int JJTELEMENTNAMEORWILDCARD = 178;
  public int JJTSCHEMAELEMENTTEST = 179;
  public int JJTELEMENTDECLARATION = 180;
  public int JJTATTRIBUTENAME = 181;
  public int JJTELEMENTNAME = 182;
  public int JJTTYPENAME = 183;
  public int JJTURILITERAL = 184;
  public int JJTREVALIDATIONDECL = 185;
  public int JJTINSERTEXPRTARGETCHOICE = 186;
  public int JJTINSERTEXPR = 187;
  public int JJTDELETEEXPR = 188;
  public int JJTREPLACEEXPR = 189;
  public int JJTRENAMEEXPR = 190;
  public int JJTSOURCEEXPR = 191;
  public int JJTTARGETEXPR = 192;
  public int JJTNEWNAMEEXPR = 193;
  public int JJTTRANSFORMEXPR = 194;
  public int JJTNCNAME = 195;
  public int JJTQNAME = 196;
  public int JJTFUNCTIONQNAME = 197;


  public String[] jjtNodeName = {
    "START",
    "QueryList",
    "Module",
    "VersionDecl",
    "StringLiteral",
    "MainModule",
    "LibraryModule",
    "ModuleDecl",
    "Prolog",
    "Setter",
    "Import",
    "Separator",
    "NamespaceDecl",
    "BoundarySpaceDecl",
    "DefaultNamespaceDecl",
    "OptionDecl",
    "OrderingModeDecl",
    "EmptyOrderDecl",
    "Greatest",
    "Least",
    "CopyNamespacesDecl",
    "PreserveMode",
    "InheritMode",
    "DefaultCollationDecl",
    "BaseURIDecl",
    "SchemaImport",
    "SchemaPrefix",
    "ModuleImport",
    "VarDecl",
    "External",
    "ConstructionDecl",
    "FunctionDecl",
    "ParamList",
    "Param",
    "EnclosedExpr",
    "Lbrace",
    "Rbrace",
    "QueryBody",
    "Expr",
    "void",
    "FLWORExpr10",
    "ForClause",
    "PositionalVar",
    "LetClause",
    "WhereClause",
    "OrderByClause",
    "OrderSpecList",
    "OrderSpec",
    "OrderModifier",
    "Ascending",
    "Descending",
    "QuantifiedExpr",
    "TypeswitchExpr",
    "CaseClause",
    "IfExpr",
    "OrExpr",
    "AndExpr",
    "ComparisonExpr",
    "RangeExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnionExpr",
    "IntersectExceptExpr",
    "InstanceofExpr",
    "TreatExpr",
    "CastableExpr",
    "CastExpr",
    "UnaryExpr",
    "Minus",
    "Plus",
    "ValidateExpr",
    "ValidationMode",
    "ExtensionExpr",
    "Pragma",
    "PragmaOpen",
    "S",
    "SForPragma",
    "PragmaClose",
    "PragmaContents",
    "ExtensionContentChar",
    "PathExpr",
    "Slash",
    "SlashSlash",
    "StepExpr",
    "ForwardAxis",
    "AbbrevForwardStep",
    "ReverseAxis",
    "AbbrevReverseStep",
    "NodeTest",
    "NameTest",
    "Wildcard",
    "NCNameColonStar",
    "StarColonNCName",
    "PredicateList",
    "Predicate",
    "IntegerLiteral",
    "DecimalLiteral",
    "DoubleLiteral",
    "VarName",
    "ParenthesizedExpr",
    "ContextItemExpr",
    "OrderedExpr",
    "UnorderedExpr",
    "FunctionCall",
    "Constructor",
    "DirectConstructor",
    "DirElemConstructor",
    "LessThanOpOrTagO",
    "StartTagOpen",
    "TagQName",
    "EmptyTagClose",
    "StartTagClose",
    "EndTagQName",
    "DirAttributeList",
    "ValueIndicator",
    "DirAttributeValue",
    "OpenQuot",
    "EscapeQuot",
    "CloseQuot",
    "OpenApos",
    "EscapeApos",
    "CloseApos",
    "QuotAttrValueContent",
    "QuotAttrContentChar",
    "AposAttrValueContent",
    "AposAttrContentChar",
    "DirElemContent",
    "ElementContentChar",
    "CommonContent",
    "PredefinedEntityRef",
    "CharRef",
    "LCurlyBraceEscape",
    "RCurlyBraceEscape",
    "DirCommentConstructor",
    "XmlCommentStartForElementContent",
    "XmlCommentStart",
    "XmlCommentEnd",
    "DirCommentContents",
    "CommentContentChar",
    "CommentContentCharDash",
    "DirPIConstructor",
    "ProcessingInstructionStartForElementContent",
    "ProcessingInstructionStart",
    "PITarget",
    "SForPI",
    "ProcessingInstructionEnd",
    "DirPIContents",
    "PIContentChar",
    "CDataSection",
    "CdataSectionStartForElementContent",
    "CdataSectionStart",
    "CdataSectionEnd",
    "CDataSectionContents",
    "CDataSectionChar",
    "ComputedConstructor",
    "CompDocConstructor",
    "CompElemConstructor",
    "ContentExpr",
    "CompAttrConstructor",
    "CompTextConstructor",
    "CompCommentConstructor",
    "CompPIConstructor",
    "SingleType",
    "TypeDeclaration",
    "SequenceType",
    "OccurrenceIndicator",
    "ItemType",
    "AtomicType",
    "AnyKindTest",
    "DocumentTest",
    "TextTest",
    "CommentTest",
    "PITest",
    "AttributeTest",
    "AttribNameOrWildcard",
    "SchemaAttributeTest",
    "AttributeDeclaration",
    "ElementTest",
    "ElementNameOrWildcard",
    "SchemaElementTest",
    "ElementDeclaration",
    "AttributeName",
    "ElementName",
    "TypeName",
    "URILiteral",
    "RevalidationDecl",
    "InsertExprTargetChoice",
    "InsertExpr",
    "DeleteExpr",
    "ReplaceExpr",
    "RenameExpr",
    "SourceExpr",
    "TargetExpr",
    "NewNameExpr",
    "TransformExpr",
    "NCName",
    "QName",
    "FunctionQName",
  };
}
/* JavaCC - OriginalChecksum=18d245eb43392aad0d7ecc4fffbb29e6 (do not edit this line) */
